# Generated by Django 3.2.7 on 2021-10-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211023_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='user',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
